name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build & Deploy
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Install .NET Framework Build Tools
        run: |
          choco install visualstudio2017buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools --includeRecommended --includeOptional --quiet --norestart"
          choco install visualstudio2017-workload-netweb --package-parameters "--includeRecommended --includeOptional --quiet --norestart"
 
      - name: Restore NuGet packages
        run: nuget restore EncryptionTool.sln

      - name: Build Application
        run: |
          msbuild EncryptionTool/EncryptionTool.csproj /p:Configuration=Release

      - name: Publish Application
        run: |
          msbuild EncryptionTool/EncryptionTool.csproj /t:Publish /p:Configuration=Release /p:PublishDir=./EncryptionTool/publish

      - name: Compress published files
        run: |
          cd EncryptionTool
          tar -czvf my-app.zip *

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/AWSCLIV2.msi" -o "AWSCLIV2.msi"
          msiexec /i AWSCLIV2.msi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy to AWS Elastic Beanstalk
        run: |
          aws s3 cp EncryptionTool/my-app.zip s3://elasticbeanstalk-eu-north-1-471112929606/my-app.zip
          aws elasticbeanstalk create-application-version --application-name MyApp --version-label ${{ github.sha }} --source-bundle S3Bucket=elasticbeanstalk-eu-north-1-471112929606,S3Key=my-app.zip
          aws elasticbeanstalk update-environment --application-name MyApp --environment-name MyEnvironment --version-label ${{ github.sha }}
