name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: 
         - master 

jobs:
  deploy:
    name: Build & Deploy
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
  
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
          
      - name: Install required workloads
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-6.0
          
      - name: Build and Publish Application
        run: |
          cd EncryptionTool
          dotnet restore
          dotnet build
          dotnet publish -c Release -o ./publish

      - name: Install AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
  
      - name: Deploy to AWS Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version --application-name MyApp --version-label v1 --source-bundle S3Bucket=elasticbeanstalk-us-west-2-123456789012,S3Key=my-app.zip
          aws elasticbeanstalk update-environment --application-name MyApp --environment-name MyEnvironment --version-label v1
